// FieldSurvey Analyses Catalog — central registry.
// Single source of truth for the Catalog drawer, Analyze tab, Saved Views,
// spec doc, and the future writing-plans output.
//
// To add a card: append an entry; nothing else needs to change in the
// registry resolver. Implement the viz component, register it in
// lib/analyses/viz-registry.ts, and (optionally) implement the compute fn.

import type { CardDescriptor, SpatialCardCatalogEntry } from "./types";

const M = false; // mobileVisible — all Analyze cards are desktop-only.

export const ANALYSES_REGISTRY: Array<CardDescriptor | SpatialCardCatalogEntry> = [
  // ───────────────────────────────────────────────────────────────────────────
  // Cornerstone
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A0_colorizer",
    section: "cornerstone",
    name: "Question Colorizer",
    short: "Pick a question — color every map point by the answer.",
    requiredInputs: ["responses", "raw_data_key_categorical"],
    nMin: 10,
    roleGate: "guest",
    mobileVisible: M,
    computeStrategy: "client",
    vizComponent: "A0ColorizerPlaceholder",
    defaultPack: true,
    m7Wave1: false,
    stub: true,
    trustSignals: ["n_non_null", "pct_missing", "classification_method"],
    pitfalls: [
      "Equal-interval breaks on skewed numerics hide variation — use quantile",
      "Categorical with >12 classes becomes a rainbow — collapse rare values first",
    ],
    sourceInspiration: "Mapbox + Felt graduated-symbol patterns",
    cardOrder: 0,
    toolbox: "symbology",
    previewImage: {
      src: "/analyses-previews/A0_colorizer.png",
      alt: "U.S. counties colored on a blue–red ramp by 2004–2016 presidential vote margin.",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:U.S._Presidential_election_margin,_2004-2016.png",
      sourceTitle: "Wikimedia Commons — Bplewe",
      license: "CC-BY-SA-4.0",
    },
    questionsAnswered: [
      "What did each respondent answer to a chosen question, mapped to their location?",
      "Are certain answers concentrated in specific areas?",
    ],
    whatItDoes:
      "Infers the question's data type (categorical, Likert, numeric, boolean, date) and " +
      "picks a sensible classification (quantile, equal-interval, or Jenks natural breaks) and " +
      "color ramp. Every map point is colored by its answer. Missing values render grey.",
    inputRequirements: [
      "1 question from the survey response schema",
      "≥10 geocoded responses",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "classification", type: "select", label: "Classification",
        options: [
          { value: "quantile", label: "Quantile (default)" },
          { value: "equal_interval", label: "Equal interval" },
          { value: "natural_breaks", label: "Jenks natural breaks" },
        ],
        defaultValue: "quantile" },
      { key: "classCount", type: "select", label: "Class count",
        options: [
          { value: 3, label: "3" }, { value: 5, label: "5" },
          { value: 7, label: "7" }, { value: 9, label: "9" },
        ],
        defaultValue: 5 },
    ],
  },

  // Existing UI we keep — match-status donut
  {
    id: "match_donut",
    section: "cornerstone",
    name: "Match-status composition",
    short: "M1 / F1 / R1 donut — the canonical project KPI.",
    requiredInputs: ["match_status"],
    nMin: 0,
    roleGate: "guest",
    mobileVisible: M,
    computeStrategy: "client",
    vizComponent: "MatchDonut",
    defaultPack: true,
    m7Wave1: true,
    stub: false,
    trustSignals: ["n", "last_updated"],
    pitfalls: ["R1 without an F1 chase queue means stale 'don't revisit' is invisible"],
    sourceInspiration: "Keystone G1/G2/G3 semantics",
    cardOrder: 1,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // Spatial Analysis Toolbox (M7.2 — Wave 0 placeholders, real compute in Wave 1-4)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "S1_autocorr",
    section: "spatial",
    name: "Spatial Autocorrelation",
    short: "Is this answer spatially clustered at all? (Moran's I + Geary's C)",
    requiredInputs: ["points", "responses"],
    nMin: 30,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S1Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["n_permutations", "weights_type", "p_value_method"],
    pitfalls: ["Moran's I assumes stationarity — non-stationary fields mislead it."],
    sourceInspiration: "PySAL esda — Moran / Geary",
    cardOrder: 100,
    toolbox: "analyzing_patterns",
    previewImage: {
      src: "/analyses-previews/S1_autocorr.png",
      alt: "Moran's I scatterplot of crime rates by neighborhood, Columbus, OH.",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Moran_ScatterPlot_Columbus_Crime.PNG",
      sourceTitle: "Wikimedia Commons — Lgalvis74",
      license: "Public Domain",
    },
    questionsAnswered: [
      "Is the answer to this question spatially clustered, dispersed, or random?",
      "Should I even look at local cluster maps for this question?",
    ],
    whatItDoes:
      "Computes Moran's I and Geary's C with a 999-permutation null distribution. " +
      "Both global statistics are shown — agreement signals a stationary spatial pattern; " +
      "disagreement flags non-stationarity. Renders a single KPI tile with a clustered / " +
      "dispersed / random / non-stationary verdict.",
    inputRequirements: [
      "1 question (numeric, Likert, or binary)",
      "Spatial weights matrix (auto-built on first use)",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "weightsType", type: "select", label: "Spatial weights",
        options: [
          { value: "knn8", label: "k-Nearest Neighbors (k=8) — default" },
          { value: "dband_500m", label: "Distance band 500 m" },
          { value: "queen", label: "Queen contiguity (zones)" },
        ],
        defaultValue: "knn8" },
      { key: "nPermutations", type: "select", label: "Permutations",
        options: [
          { value: 999, label: "999 (interactive, default)" },
          { value: 9999, label: "9 999 (publish-grade, slower)" },
        ],
        defaultValue: 999 },
    ],
  },
  {
    id: "S2_gi_star_q",
    section: "spatial",
    name: "Hot/Cold Spot Analysis (Getis-Ord Gi*)",
    short: "Where are the statistically significant clusters of high or low values?",
    requiredInputs: ["points", "responses"],
    nMin: 30,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S2Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["n_units", "weights_type", "fdr_corrected", "fdr_cutoff"],
    pitfalls: [
      "Without FDR correction Gi* over-flags at α·n rate — FDR is non-negotiable.",
      "MAUP — results change with aggregation level.",
    ],
    sourceInspiration: "Getis-Ord 1992; PySAL esda.G_Local; esda.fdr",
    cardOrder: 200,
    toolbox: "mapping_clusters",
    previewImage: {
      src: "/analyses-previews/S2_gi_star_q.jpg",
      alt: "Getis-Ord Gi* hot-spot / cold-spot map of estimated U.S. county unemployment, 2020.",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:USA_Contiguous_Unemployment_Rate_2020.jpg",
      sourceTitle: "Wikimedia Commons — GeogSage",
      license: "CC-BY-4.0",
    },
    questionsAnswered: [
      "Where are the statistically significant clusters of high values?",
      "Where are the statistically significant clusters of low values?",
      "Which spots are noise vs real?",
    ],
    whatItDoes:
      "Runs the Getis-Ord Gi* local statistic against your spatial weights matrix " +
      "with 999 permutations. Applies a False Discovery Rate (FDR) cutoff via PySAL's " +
      "esda.fdr so the map doesn't over-flag at the α·n rate. Each point is labeled " +
      "hot, cold, or insignificant.",
    inputRequirements: [
      "1 question (numeric, Likert, or binary)",
      "Spatial weights matrix (auto-built on first use)",
      "FDR alpha (default 0.05)",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "fdrAlpha", type: "slider", label: "FDR alpha", min: 0.01, max: 0.10, step: 0.01, defaultValue: 0.05 },
      { key: "weightsType", type: "select", label: "Spatial weights",
        options: [
          { value: "knn8", label: "k-Nearest Neighbors (k=8) — default" },
          { value: "dband_500m", label: "Distance band 500 m" },
        ],
        defaultValue: "knn8" },
      { key: "nPermutations", type: "select", label: "Permutations",
        options: [
          { value: 999, label: "999 (interactive, default)" },
          { value: 9999, label: "9 999 (publish-grade, slower)" },
        ],
        defaultValue: 999 },
    ],
  },
  {
    id: "S3_lisa_q",
    section: "spatial",
    name: "Cluster & Outlier Analysis (LISA)",
    short: "Where do neighborhoods agree, and where is a single block an outlier?",
    requiredInputs: ["points", "responses"],
    nMin: 30,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S3Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["n_HH", "n_LL", "n_HL", "n_LH", "fdr_cutoff"],
    pitfalls: [
      "Significant cells mark cluster CORES, not extents — legend must say 'cores'.",
      "FDR cutoff required to avoid over-flagging.",
    ],
    sourceInspiration: "Anselin 1995; PySAL esda.Moran_Local",
    cardOrder: 300,
    toolbox: "mapping_clusters",
    previewImage: {
      src: "/analyses-previews/S3_lisa_q.jpg",
      alt: "Anselin Local Moran cluster map of U.S. county poverty 2020, showing HH/LL/HL/LH categories.",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:USA_Contiguous_Poverty_2020_clusters.jpg",
      sourceTitle: "Wikimedia Commons — GeogSage",
      license: "CC-BY-SA-4.0",
    },
    questionsAnswered: [
      "Where do neighbors all give the same high answer (HH cluster)?",
      "Where do neighbors all give the same low answer (LL cluster)?",
      "Where is a single block an outlier — high in a low neighborhood, or vice versa?",
    ],
    whatItDoes:
      "Computes the Anselin Local Moran's I per point and categorizes each as HH (high-high cluster), " +
      "LL (low-low cluster), HL (high outlier surrounded by low), LH (low outlier surrounded by high), " +
      "or not significant. FDR-corrected via PySAL esda.fdr.",
    inputRequirements: [
      "1 question (numeric, Likert, or binary)",
      "Spatial weights matrix (auto-built on first use)",
      "FDR alpha (default 0.05)",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "fdrAlpha", type: "slider", label: "FDR alpha", min: 0.01, max: 0.10, step: 0.01, defaultValue: 0.05 },
      { key: "weightsType", type: "select", label: "Spatial weights",
        options: [
          { value: "knn8", label: "k-Nearest Neighbors (k=8) — default" },
          { value: "dband_500m", label: "Distance band 500 m" },
        ],
        defaultValue: "knn8" },
      { key: "nPermutations", type: "select", label: "Permutations",
        options: [
          { value: 999, label: "999 (interactive, default)" },
          { value: 9999, label: "9 999 (publish-grade, slower)" },
        ],
        defaultValue: 999 },
    ],
  },
  {
    id: "S4_satscan",
    section: "spatial",
    name: "Spatial Scan Statistic (Kulldorff)",
    short: "Where is the biggest geographic excess of a response, ignoring admin boundaries?",
    requiredInputs: ["points", "responses"],
    nMin: 100,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S4Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["model_used", "max_window_pct", "n_permutations", "n_clusters"],
    pitfalls: [
      "Without max-window cap, the MLE circle inflates to half the study area on sparse data.",
      "Bernoulli model needs a binary case/control; Poisson needs an exposure denominator.",
    ],
    sourceInspiration: "Kulldorff 1997 — A Spatial Scan Statistic; SaTScan CLI",
    cardOrder: 400,
    toolbox: "mapping_clusters",
    previewImage: {
      src: "/analyses-previews/S4_satscan.svg",
      alt: "Schematic showing two red circular scan windows over a light-grey polygon basemap, the primary thicker than the secondary.",
      sourceUrl: "https://www.satscan.org/papers/k-cstm1997.pdf",
      sourceTitle: "Custom illustration — based on Kulldorff 1997",
      license: "Custom-by-us",
    },
    questionsAnswered: [
      "Where is the most concentrated cluster of 'yes' (or 'high') answers — without pre-defining zones?",
      "Are there secondary clusters worth investigating?",
    ],
    whatItDoes:
      "Runs Kulldorff's spatial scan statistic via the SaTScan CLI. Bernoulli model for binary answers; " +
      "Poisson model when a universe denominator exists. Returns the primary cluster (circle on the map) " +
      "with its relative risk, log-likelihood ratio, and p-value, plus secondary clusters.",
    inputRequirements: [
      "1 question (binary, or numeric with an answer threshold)",
      "≥100 geocoded responses",
      "Optional: universe for the Poisson model",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "answerOption", type: "answer_picker", label: "Answer option (for Bernoulli)", questionKeyRef: "questionKey" },
      { key: "model", type: "select", label: "Model",
        options: [
          { value: "bernoulli", label: "Bernoulli (binary case/control) — default" },
          { value: "poisson", label: "Poisson (needs universe denominator)" },
        ],
        defaultValue: "bernoulli" },
      { key: "maxWindowPct", type: "slider", label: "Max window (% of population)",
        min: 0.10, max: 0.50, step: 0.05, defaultValue: 0.25 },
    ],
  },

  {
    id: "S5_distance_decay",
    section: "spatial",
    name: "Distance-Decay vs Point of Interest",
    short: "Does the answer depend on distance from a chosen point?",
    requiredInputs: ["points", "responses"],
    nMin: 50,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S5Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["n_permutations", "bin_edges_km", "envelope_method"],
    pitfalls: [
      "Modifiable distance bins — results change with bucket edges. We use fixed log-spaced bins.",
      "Without a permutation-POI envelope, even random data looks like a trend.",
    ],
    sourceInspiration: "Standard distance-decay from spatial epidemiology",
    cardOrder: 500,
    toolbox: "spatial_relationships",
    previewImage: {
      src: "/analyses-previews/S5_distance_decay.svg",
      alt: "Schematic line chart showing a descending response curve with a translucent grey 95 percent envelope band and a star marker at distance zero.",
      sourceUrl: "",
      sourceTitle: "Custom illustration",
      license: "Custom-by-us",
    },
    questionsAnswered: [
      "Do responses change with distance from a feature (e.g. proposed site, hazard)?",
      "Is the apparent distance-decay real or could it occur by chance?",
    ],
    whatItDoes:
      "Admin drops a point of interest. Each respondent's distance to the POI is computed and " +
      "binned into fixed log-spaced bins (0.25, 0.5, 1, 2, 4 km). Mean answer ± SE is plotted per " +
      "bin. A 999-permutation envelope of random POIs (sampled within the project boundary) is " +
      "overlaid so admins can tell signal from noise.",
    inputRequirements: [
      "1 question (numeric or Likert)",
      "1 point of interest (drop on the map or type lat/lon)",
      "Project boundary (for the permutation envelope sampler)",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "poi", type: "poi_picker", label: "Point of interest" },
      { key: "nPermutations", type: "select", label: "Permutations",
        options: [
          { value: 999, label: "999 (interactive, default)" },
          { value: 9999, label: "9 999 (publish-grade, slower)" },
        ],
        defaultValue: 999 },
    ],
  },
  {
    id: "S6_coverage_response",
    section: "spatial",
    name: "Coverage × Response Bivariate",
    short: "Did we BOTH cover the universe AND get representative answers?",
    requiredInputs: ["points", "responses", "universe", "parcels"],
    nMin: 10,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "postgres",
    vizComponent: "S6Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["zone_unit", "n_suppressed_zones", "denominator_definition"],
    pitfalls: [
      "Zone size — too fine = many suppressed; too coarse = invisible patterns.",
      "Zones with n<10 respondents are suppressed for stability.",
    ],
    sourceInspiration: "AAPOR nonresponse subcommittee; CDC PLACES bivariate methodology",
    cardOrder: 600,
    toolbox: "coverage_equity",
    previewImage: {
      src: "/analyses-previews/S6_coverage_response.png",
      alt: "Bivariate choropleth of U.S. counties showing the joint distribution of Black and Hispanic population share.",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Black_Hispanic_Bivariate_Map.png",
      sourceTitle: "Wikimedia Commons — Bplewe",
      license: "CC-BY-SA-4.0",
    },
    questionsAnswered: [
      "Where did we both knock enough doors AND get a representative share of a chosen answer?",
      "Where is high coverage masking biased composition?",
    ],
    whatItDoes:
      "Per block group (default; admin can switch to tract or H3), computes (% universe touched) " +
      "tertile × (% responders picking option X) tertile. Renders a 3×3 bivariate choropleth — " +
      "9 categories from low/low (dark grey) to high/high (deep purple). Zones with n<10 are " +
      "suppressed.",
    inputRequirements: [
      "1 question + 1 answer option",
      "Universe upload",
      "Parcels or census polygons",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "answerOption", type: "answer_picker", label: "Answer option", questionKeyRef: "questionKey" },
      { key: "zoneUnit", type: "select", label: "Zone unit",
        options: [
          { value: "block_group", label: "Block group (default)" },
          { value: "tract", label: "Census tract" },
          { value: "h3_8", label: "H3 hex res 8" },
        ],
        defaultValue: "block_group" },
      { key: "minN", type: "slider", label: "Min n per zone (suppress below)",
        min: 5, max: 30, step: 1, defaultValue: 10 },
    ],
  },
  {
    id: "S7_local_geary",
    section: "spatial",
    name: "Local Geary Heterogeneity",
    short: "Does this respondent agree with their geographic neighbors?",
    requiredInputs: ["points", "responses"],
    nMin: 30,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S7Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["n_pos_autocorr", "n_neg_autocorr", "winsorize_pct", "fdr_cutoff"],
    pitfalls: [
      "Local Geary is sensitive to outliers in the answer value — winsorize unless you opt out.",
    ],
    sourceInspiration: "Anselin 1995; PySAL esda.Geary_Local",
    cardOrder: 700,
    toolbox: "mapping_clusters",
    previewImage: {
      src: "/analyses-previews/S7_local_geary.svg",
      alt: "Schematic hex mosaic using a teal-to-magenta diverging palette, with cells where neighbors agree shown in teal and cells where they differ shown in magenta.",
      sourceUrl: "",
      sourceTitle: "Custom illustration",
      license: "Custom-by-us",
    },
    questionsAnswered: [
      "Which respondents have neighbors who agree with them (positive local autocorrelation)?",
      "Which respondents differ sharply from their neighbors (negative local autocorrelation / heterogeneity)?",
    ],
    whatItDoes:
      "Computes the Local Geary c_i statistic per point — small c_i means you agree with " +
      "neighbors (positive autocorrelation), large means you differ. Winsorizes continuous " +
      "answers at the 2nd / 98th percentile by default. FDR-corrected via PySAL esda.fdr.",
    inputRequirements: [
      "1 question (numeric or Likert)",
      "Spatial weights matrix (auto-built on first use)",
      "FDR alpha (default 0.05)",
    ],
    settingsSchema: [
      { key: "questionKey", type: "question_picker", label: "Question", defaultValue: "inherit_global" },
      { key: "fdrAlpha", type: "slider", label: "FDR alpha", min: 0.01, max: 0.10, step: 0.01, defaultValue: 0.05 },
      { key: "winsorize", type: "toggle", label: "Winsorize at 2nd/98th percentile", defaultValue: true },
      { key: "nPermutations", type: "select", label: "Permutations",
        options: [
          { value: 999, label: "999 (interactive, default)" },
          { value: 9999, label: "9 999 (publish-grade, slower)" },
        ],
        defaultValue: 999 },
    ],
  },
  {
    id: "S8_bivariate",
    section: "spatial",
    name: "Bivariate Spatial Association (Lee's L)",
    short: "Do answers to two questions co-cluster spatially?",
    requiredInputs: ["points", "responses"],
    nMin: 50,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "S8Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: ["lee_L", "pearson_r", "disagreement_flag", "n_significant"],
    pitfalls: [
      "Lee's L and Pearson r disagreement is the whole point — surface it loudly.",
    ],
    sourceInspiration: "Lee 2001; ArcGIS Pro Bivariate Spatial Association; PySAL Moran_Local_BV",
    cardOrder: 800,
    toolbox: "spatial_relationships",
    previewImage: {
      src: "/analyses-previews/S8_bivariate.svg",
      alt: "Schematic hex mosaic using a four-class palette (dark red HH, dark blue LL, pink HL, light blue LH) with a small two-variable inset.",
      sourceUrl: "",
      sourceTitle: "Custom illustration",
      license: "Custom-by-us",
    },
    questionsAnswered: [
      "Where are two questions co-clustered (both high together, or both low together)?",
      "Are the questions correlated but NOT spatially co-located?",
    ],
    whatItDoes:
      "Computes Lee's L (preferred) or Bivariate Local Moran for the chosen pair of questions. " +
      "Reports the global Lee's L AND the Pearson r — divergence between them is informative " +
      "(strong correlation but weak Lee's L means correlated but not spatially co-located).",
    inputRequirements: [
      "2 questions (numeric or Likert)",
      "Spatial weights matrix (auto-built on first use)",
    ],
    settingsSchema: [
      { key: "questionKeyX", type: "question_picker", label: "Question X" },
      { key: "questionKeyY", type: "question_picker", label: "Question Y" },
      { key: "fdrAlpha", type: "slider", label: "FDR alpha", min: 0.01, max: 0.10, step: 0.01, defaultValue: 0.05 },
      { key: "nPermutations", type: "select", label: "Permutations",
        options: [
          { value: 999, label: "999 (interactive, default)" },
          { value: 9999, label: "9 999 (publish-grade, slower)" },
        ],
        defaultValue: 999 },
    ],
  },

  // v2 placeholder entries — visible (greyed) in the modal so users see the roadmap.
  {
    id: "V2_emerging_hot",
    section: "spatial",
    name: "Emerging Hot Spot Analysis (v2)",
    short: "Spatio-temporal Gi* — where are response patterns changing over time?",
    requiredInputs: ["points", "responses", "timestamps_n_days"],
    nMin: 100,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "V2Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: [],
    pitfalls: ["Requires longitudinal panels — most surveys are one-shot."],
    sourceInspiration: "ArcGIS Pro Emerging Hot Spot",
    cardOrder: 900,
    toolbox: "space_time",
    previewImage: {
      src: "/analyses-previews/V2_emerging_hot.svg",
      alt: "Placeholder — coming in v2.",
      sourceUrl: "",
      sourceTitle: "Coming soon",
      license: "Custom-by-us",
    },
    questionsAnswered: ["v2 — see roadmap."],
    whatItDoes: "Coming in v2. Requires a longitudinal time series of responses.",
    inputRequirements: [">3 months of response data"],
    settingsSchema: [],
  },
  {
    id: "V2_gwr",
    section: "spatial",
    name: "Geographically Weighted Regression (v2)",
    short: "Where does the relationship between two questions break down across space?",
    requiredInputs: ["points", "responses"],
    nMin: 200,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "V2Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: [],
    pitfalls: ["Bandwidth cross-validation is O(n^2)–O(n^3); not a tile compute."],
    sourceInspiration: "Brunsdon/Fotheringham GWR; PySAL mgwr",
    cardOrder: 910,
    toolbox: "spatial_regression",
    previewImage: {
      src: "/analyses-previews/V2_gwr.svg",
      alt: "Placeholder — coming in v2.",
      sourceUrl: "",
      sourceTitle: "Coming soon",
      license: "Custom-by-us",
    },
    questionsAnswered: ["v2 — see roadmap."],
    whatItDoes: "Coming in v2.",
    inputRequirements: [],
    settingsSchema: [],
  },
  {
    id: "V2_segregation",
    section: "spatial",
    name: "Segregation Indices (v2)",
    short: "Dissimilarity / isolation by response group.",
    requiredInputs: ["points", "responses"],
    nMin: 200,
    roleGate: "member",
    mobileVisible: M,
    computeStrategy: "python_sidecar",
    vizComponent: "V2Placeholder",
    defaultPack: false,
    m7Wave1: false,
    stub: true,
    trustSignals: [],
    pitfalls: ["Vertical-leaning — not universally applicable."],
    sourceInspiration: "Massey-Denton 1988",
    cardOrder: 920,
    toolbox: "sampling_equity",
    previewImage: {
      src: "/analyses-previews/V2_segregation.svg",
      alt: "Placeholder — coming in v2.",
      sourceUrl: "",
      sourceTitle: "Coming soon",
      license: "Custom-by-us",
    },
    questionsAnswered: ["v2 — see roadmap."],
    whatItDoes: "Coming in v2.",
    inputRequirements: [],
    settingsSchema: [],
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §1 Response analytics
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A1_univariate",
    section: "response", name: "Univariate distribution",
    short: "% breakdown per categorical / Likert question.",
    requiredInputs: ["responses", "raw_data_key_categorical"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "DivergingBar",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["n", "pct_missing", "wilson_ci"],
    pitfalls: ["Mean-of-Likert is meaningless — show diverging bars anchored at neutral"],
    sourceInspiration: "Qualtrics + Kobo Default Report",
    cardOrder: 10,
  },
  {
    id: "A2_numeric_summary",
    section: "response", name: "Numeric summary",
    short: "Histogram + boxplot + median/IQR per numeric column.",
    requiredInputs: ["responses", "raw_data_key_numeric"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "HistogramBoxplot",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["n", "median", "iqr", "pct_missing"],
    pitfalls: ["Outliers drag means; default to median", "ZIP codes parsed as numeric"],
    sourceInspiration: "Wilke — Fundamentals of Data Visualization ch. 7",
    cardOrder: 11,
  },
  {
    id: "A3_multiselect_upset",
    section: "response", name: "Multi-select co-occurrence",
    short: "UpSet plot for which option combinations co-occur.",
    requiredInputs: ["responses", "raw_data_key_multi"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "UpSetPlot",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["n", "% of respondents picking option"],
    pitfalls: ["Percentages summing >100 confuses users", "Treat each option as binary, not nominal"],
    sourceInspiration: "Lex et al. 2014 UpSet",
    cardOrder: 12,
  },
  {
    id: "A4_crosstab_chi2",
    section: "response", name: "Cross-tab with χ² / Fisher",
    short: "Contingency heatmap + effect size + significance.",
    requiredInputs: ["responses", "raw_data_key_categorical"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "CrossTabHeatmap",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_per_cell", "expected_count", "fdr_warning"],
    pitfalls: ["p-hacking by clicking every pair", "Tiny expected counts inflate χ²"],
    sourceInspiration: "Groves et al. Survey Methodology",
    cardOrder: 13,
  },
  {
    id: "A5_response_drift",
    section: "response", name: "Response drift over time",
    short: "Did answers shift as the field period progressed?",
    requiredInputs: ["responses", "timestamps_n_days"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "DriftAreaLine",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_per_period"],
    pitfalls: ["Collection-time drift (coverage shift) ≠ attitudinal drift"],
    sourceInspiration: "AAPOR mode-effects literature",
    cardOrder: 14,
  },
  {
    id: "A6_text_ngrams",
    section: "response", name: "Open-text n-grams + topic model",
    short: "Ranked unigram/bigram bars; optional BERTopic topics.",
    requiredInputs: ["responses", "raw_data_key_text"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "NgramTopics",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_text", "pct_empty"],
    pitfalls: ["Word clouds look like analysis but only show frequency — we ship ranked bars instead"],
    sourceInspiration: "arXiv:2501.13777 topic models for complex surveys",
    cardOrder: 15,
  },
  {
    id: "A7_weighted_vs_unweighted",
    section: "response", name: "Weighted vs unweighted",
    short: "How estimates change when sample is raked to ACS.",
    requiredInputs: ["responses", "demographics_schema", "acs_tract_profile"],
    nMin: 200, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "WeightedDeltaBars",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["deff", "effective_n", "max_min_weight_ratio"],
    pitfalls: ["Raking on too many margins → extreme weights"],
    sourceInspiration: "Lumley `survey` R package",
    cardOrder: 16,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §2 Spatial analytics
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A8_gi_star",
    section: "spatial", name: "Getis-Ord Gi* hot/cold spots",
    short: "Statistically significant clusters of high or low values.",
    requiredInputs: ["points", "parcels"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "SignificanceChoropleth",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["n_units", "weights_type", "fdr_corrected"],
    pitfalls: ["MAUP — results change with aggregation level", "Multiple testing without FDR inflates 'significant' spots"],
    sourceInspiration: "ArcGIS Hot Spot Analysis docs; PySAL esda",
    cardOrder: 20,
  },
  {
    id: "A9_lisa",
    section: "spatial", name: "LISA cluster + outlier map",
    short: "HH / LL / HL / LH local-Moran categories.",
    requiredInputs: ["points", "parcels"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "LisaMap",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_units", "n_permutations", "pseudo_p"],
    pitfalls: ["HL ('high surrounded by low') is an outlier, not a hot-spot — easy to misread"],
    sourceInspiration: "Anselin 1995; PySAL esda",
    cardOrder: 21,
  },
  {
    id: "A10_global_moran",
    section: "spatial", name: "Global Moran's I tile",
    short: "Single KPI — clustered, dispersed, or random?",
    requiredInputs: ["points", "parcels"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "MoranTile",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_units", "z_score", "p_value", "weights_type"],
    pitfalls: ["A significant Moran's I doesn't say where the clusters are — pair with A8 or A9"],
    sourceInspiration: "PySAL esda",
    cardOrder: 22,
  },
  {
    id: "A11_kde",
    section: "spatial", name: "KDE heatmap",
    short: "Kernel density estimation overlay — fixed or adaptive.",
    requiredInputs: ["points"],
    nMin: 200, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "KdeRaster",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["bandwidth_m", "method", "n"],
    pitfalls: ["Bandwidth choice drives the visual conclusion — expose the slider"],
    sourceInspiration: "EPI 563 Spatial Epi — KDE chapter",
    cardOrder: 23,
  },
  {
    id: "A12_choropleth_agg",
    section: "spatial", name: "Choropleth aggregation",
    short: "Roll points up to parcel / block-group / tract.",
    requiredInputs: ["points", "parcels"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "Choropleth",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["unit", "class_break_method", "n_per_unit"],
    pitfalls: ["Raw counts in tiny tracts mislead — suppress denominators <5"],
    sourceInspiration: "Tobler / MAUP literature",
    cardOrder: 24,
  },
  {
    id: "A13_cov_heatmap",
    section: "spatial", name: "Coverage-vs-universe heatmap",
    short: "% universe touched per block.",
    requiredInputs: ["universe", "points", "parcels"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "RateChoropleth",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["denominator", "suppression_threshold"],
    pitfalls: ["Uneven universe density makes % look dramatic in small blocks"],
    sourceInspiration: "ArcGIS Dashboards + Survey123 canvassing pattern",
    cardOrder: 25,
  },
  {
    id: "A14_dot_density",
    section: "spatial", name: "Dot-density overlay",
    short: "1 dot = N points, deterministically jittered within parcel.",
    requiredInputs: ["points", "parcels"],
    nMin: 200, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "DotDensity",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["dots_per_point_ratio"],
    pitfalls: ["Dots within polygon are NOT real coordinates — caption it explicitly"],
    sourceInspiration: "Census On the Map dot-density convention",
    cardOrder: 26,
  },
  {
    id: "A15_svi_cross",
    section: "spatial", name: "SVI cross-map",
    short: "Bivariate (coverage × CDC SVI) equity overlay.",
    requiredInputs: ["points", "cdc_svi_tract"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "BivariateChoropleth",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_tracts", "pearson_r_ci"],
    pitfalls: ["SVI is composite — high SVI alone tells you little about why a tract is under-covered"],
    sourceInspiration: "CDC/ATSDR Social Vulnerability Index",
    cardOrder: 27,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §3 Coverage & completion (AAPOR)
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A16_rr",
    section: "coverage", name: "AAPOR RR1 / RR3 / RR5",
    short: "Three rigorous response-rate definitions.",
    requiredInputs: ["universe", "aapor_mapping", "statuses"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "AaporRatesPanel",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["I", "P", "R", "NC", "O", "UH", "UO", "formula"],
    pitfalls: ["Mis-mapping 'vacant' to ineligible inflates the rate"],
    sourceInspiration: "AAPOR Standard Definitions; outcomerate R package",
    cardOrder: 30,
  },
  {
    id: "A17_coop_ref",
    section: "coverage", name: "Cooperation + refusal (COOP1 / REF1)",
    short: "Of contacted households, who cooperated, who refused.",
    requiredInputs: ["universe", "aapor_mapping", "statuses"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "AaporCoopRefPanel",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["formula", "n_contacted"],
    pitfalls: ["REF1 conflates 'refused at door' with 'never opened door' — show sub-split"],
    sourceInspiration: "AAPOR Standard Definitions",
    cardOrder: 31,
  },
  {
    id: "A18_con",
    section: "coverage", name: "Contact rate (CON1)",
    short: "% universe households actually reached.",
    requiredInputs: ["universe", "aapor_mapping", "statuses"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "AaporContactTile",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["n_attempts", "n_universe"],
    pitfalls: ["Door-knocks without contact easily over-counted as attempts"],
    sourceInspiration: "AAPOR Standard Definitions §3",
    cardOrder: 32,
  },
  {
    id: "A19_universe_map",
    section: "coverage", name: "Universe penetration map",
    short: "Touched / not-touched / multi-touched per universe address.",
    requiredInputs: ["universe", "points"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "UniverseMap",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["touched_definition", "count_breakdown"],
    pitfalls: ["'Touched' definition (any visit vs contact) needs to be explicit"],
    sourceInspiration: "FieldSurvey M5 universe pattern",
    cardOrder: 33,
  },
  {
    id: "A20_undersampled",
    section: "coverage", name: "Under-sampled tracts ranking",
    short: "Top-N gaps between target and achieved coverage.",
    requiredInputs: ["universe", "points", "parcels"],
    nMin: 5, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "RankedBullet",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["denominator", "last_canvassed"],
    pitfalls: ["Tracts with tiny universes show as 100% deficit on tiny denominators"],
    sourceInspiration: "Stephen Few bullet-graph spec",
    cardOrder: 34,
  },
  {
    id: "A21_finish",
    section: "coverage", name: "Predicted finish date",
    short: "Monte Carlo 50 / 75 / 90% completion-date fan chart.",
    requiredInputs: ["universe", "timestamps_n_days"],
    nMin: 14, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "MonteCarloFan",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["n_simulations", "history_window", "staffing_assumption"],
    pitfalls: ["Assumes stationary velocity — ignores weekend/holiday seasonality"],
    sourceInspiration: "Scrum.org Monte Carlo forecasting",
    cardOrder: 35,
  },
  {
    id: "A22_refusal_pattern",
    section: "coverage", name: "Refusal & not-home pattern map",
    short: "3-panel small multiples (refused / not-home / vacant).",
    requiredInputs: ["points", "statuses"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "RefusalSmallMultiples",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["base_rates"],
    pitfalls: ["Refusal pattern is confounded by which surveyor went where — pair with A28"],
    sourceInspiration: "RTI falsification literature",
    cardOrder: 36,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §4 Temporal
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A23_hour_local",
    section: "temporal", name: "Hour-of-day (local tz)",
    short: "When are doors knocked? — fixes the existing UTC bug.",
    requiredInputs: ["points", "project_tz"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "HourHistogram",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["tz_label", "n", "legal_window"],
    pitfalls: ["UTC shows midnight peak that is actually 8 pm local — embarrassing trust hit"],
    sourceInspiration: "Common dashboard QA failure mode",
    cardOrder: 40,
  },
  {
    id: "A24_dow",
    section: "temporal", name: "Day-of-week heatmap",
    short: "7×24 DOW × hour pattern — are weekends covered?",
    requiredInputs: ["points", "project_tz"],
    nMin: 7, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "DowHourHeatmap",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["n", "tz_label"],
    pitfalls: ["Small n per cell looks dramatic — use sequential color, not divergent"],
    sourceInspiration: "NGP VAN / OpenField canvassing dashboards",
    cardOrder: 41,
  },
  {
    id: "A25_velocity",
    section: "temporal", name: "Velocity + change-points",
    short: "Daily rate + 7-day median ribbon + auto-detected breaks.",
    requiredInputs: ["points", "timestamps_n_days"],
    nMin: 21, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "VelocityLineCI",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["n_breaks", "ci_band", "min_segment"],
    pitfalls: ["Change-points fire on weekend dips without a minimum-segment guard"],
    sourceInspiration: "ruptures Python lib (PELT / BinSeg)",
    cardOrder: 42,
  },
  {
    id: "A26_decay",
    section: "temporal", name: "Response decay curve",
    short: "Survival-style cumulative-vs-target.",
    requiredInputs: ["responses", "timestamps_n_days"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "DecayCurve",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["universe_events"],
    pitfalls: ["Confounded by surveyor schedule rather than respondent behavior"],
    sourceInspiration: "Groves nonresponse modeling",
    cardOrder: 43,
  },
  {
    id: "A27_wow",
    section: "temporal", name: "Week-over-week trend (CI)",
    short: "Weekly bars with bootstrap 95% CI.",
    requiredInputs: ["points", "timestamps_n_days"],
    nMin: 28, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "WowBarsCI",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_per_week"],
    pitfalls: ["Small weekly n; treating CI bracket as significance test"],
    sourceInspiration: "Wilke ch. 16",
    cardOrder: 44,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §5 Surveyor / team QC
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A28_productivity",
    section: "qc", name: "Productivity bullet",
    short: "Points-per-shift-hour vs team median (per surveyor).",
    requiredInputs: ["points", "shifts"],
    nMin: 3, roleGate: "admin", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "ProductivityBullet",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["n_shifts", "team_median"],
    pitfalls: ["Raw productivity penalizes surveyors on harder turf"],
    sourceInspiration: "MiniVAN Manager",
    cardOrder: 50,
  },
  {
    id: "A29_gps_outlier",
    section: "qc", name: "GPS-accuracy outliers",
    short: "Boxplot per surveyor; >50 m flagged on map.",
    requiredInputs: ["points"],
    nMin: 30, roleGate: "admin", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "GpsOutlierBox",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["median_accuracy", "flag_threshold_m"],
    pitfalls: ["Indoor / urban canyon points are bad-GPS for legitimate reasons"],
    sourceInspiration: "Standard field-data QC",
    cardOrder: 51,
  },
  {
    id: "A30_time_per_stop",
    section: "qc", name: "Time-per-stop ridgeline",
    short: "Per-surveyor distribution; <60 s flagged.",
    requiredInputs: ["points"],
    nMin: 30, roleGate: "admin", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "TimePerStopRidgeline",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["approximation_caveat"],
    pitfalls: ["Consecutive-timestamp gap includes walking; not interaction time"],
    sourceInspiration: "2024 JSSAM Detecting Interviewer Fraud",
    cardOrder: 52,
  },
  {
    id: "A31_curbstone",
    section: "qc", name: "Curbstoning composite risk",
    short: "Multi-signal radar — never auto-flag; human-in-loop only.",
    requiredInputs: ["points", "responses"],
    nMin: 50, roleGate: "admin", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "CurbstoneRadar",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["signal_breakdown", "baseline_window", "indicator_disclaimer"],
    pitfalls: [
      "Single-signal thresholds are dangerous — composite + human review only",
      "False positives have employment consequences",
    ],
    sourceInspiration: "Murphy/Biemer 2016; AAPOR Falsification Task Force",
    cardOrder: 53,
  },
  {
    id: "A32_photo_skip",
    section: "qc", name: "Photo-skip rate vs team avg",
    short: "Per-surveyor photo coverage.",
    requiredInputs: ["points", "photos"],
    nMin: 30, roleGate: "admin", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "PhotoSkipBullet",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["team_median"],
    pitfalls: ["Legitimate refusal-to-photo inflates the score"],
    sourceInspiration: "RTI falsification system",
    cardOrder: 54,
  },
  {
    id: "A33_off_boundary",
    section: "qc", name: "Stops outside project boundary",
    short: "Off-boundary points highlighted (30 m buffer tolerance).",
    requiredInputs: ["boundary", "points"],
    nMin: 1, roleGate: "admin", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "OffBoundaryMapList",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["buffer_distance_m"],
    pitfalls: ["GPS drift legitimately pushes points across narrow edges — use buffer"],
    sourceInspiration: "MiniVAN turf-discipline",
    cardOrder: 55,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §6 Data quality
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A34_missing_heatmap",
    section: "quality", name: "Missing-data heatmap",
    short: "Question × surveyor heat — where are the holes?",
    requiredInputs: ["responses"],
    nMin: 30, roleGate: "admin", mobileVisible: M,
    computeStrategy: "client", vizComponent: "MissingHeatmap",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["structural_vs_item"],
    pitfalls: ["Skip-logic missing must be distinguished from refused — needs schema annotation"],
    sourceInspiration: "Lumley / Lohr survey methodology",
    cardOrder: 60,
  },
  {
    id: "A35_straight_line",
    section: "quality", name: "Straight-lining detector",
    short: "Matrix-question variance flag — never auto-delete.",
    requiredInputs: ["responses", "raw_data_key_categorical"],
    nMin: 30, roleGate: "admin", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "StraightLineList",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["indicator_score", "longstring_index"],
    pitfalls: ["Valid straight-lining exists — 'all 5s' can be honest"],
    sourceInspiration: "Kim et al. 2019 SSCR",
    cardOrder: 61,
  },
  {
    id: "A36_duplicate",
    section: "quality", name: "Duplicate / near-duplicate flagger",
    short: "MinHash similarity clusters; human review queue.",
    requiredInputs: ["responses"],
    nMin: 30, roleGate: "admin", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "DupClusterList",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["jaccard_threshold", "n_flagged_pairs"],
    pitfalls: ["Legitimate household members at same address"],
    sourceInspiration: "Elmagarmid et al. duplicate-record survey",
    cardOrder: 62,
  },
  {
    id: "A37_zip_mismatch",
    section: "quality", name: "ZIP-vs-coordinates mismatch",
    short: "Address ZIP vs ZCTA derived from GPS.",
    requiredInputs: ["points", "responses"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "ZipMismatchMap",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_flagged"],
    pitfalls: ["Legitimate ZIP boundary edges"],
    sourceInspiration: "Standard import-time validation",
    cardOrder: 63,
  },
  {
    id: "A38_geocode_confidence",
    section: "quality", name: "Geocode confidence × match-rate",
    short: "Binned bar — does low-confidence geocode produce more failed matches?",
    requiredInputs: ["responses", "geocode_metadata"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "GeocodeConfidenceBars",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_per_bucket"],
    pitfalls: ["Confidence is categorical, not probability"],
    sourceInspiration: "Census Geocoder docs",
    cardOrder: 64,
  },
  {
    id: "A39_freshness",
    section: "quality", name: "Freshness chrome",
    short: "'as of HH:MM' chip with green/yellow/red staleness.",
    requiredInputs: [],
    nMin: 0, roleGate: "guest", mobileVisible: M,
    computeStrategy: "client", vizComponent: "FreshnessChip",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["last_updated", "stale_threshold"],
    pitfalls: ["Users assume 'live' without checking — chrome makes staleness loud"],
    sourceInspiration: "Stephen Few dashboard chrome",
    cardOrder: 65,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §7 Representativeness
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A40_sample_vs_acs",
    section: "bias", name: "Sample-vs-ACS composition",
    short: "Side-by-side bars per demographic margin.",
    requiredInputs: ["responses", "demographics_schema", "acs_tract_profile"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "SampleVsAcsBars",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["acs_year", "acs_moe"],
    pitfalls: ["ACS 5-year averages lag; tract-level margins are wide"],
    sourceInspiration: "Census ACS Data Profiles",
    cardOrder: 70,
  },
  {
    id: "A41_whos_missing",
    section: "bias", name: "Who's-missing analysis",
    short: "Ranked deficit bar (most under-rep subgroup first).",
    requiredInputs: ["responses", "demographics_schema", "acs_tract_profile"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "WhosMissingBars",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n_per_subgroup"],
    pitfalls: ["Intersectional gaps invisible in marginals"],
    sourceInspiration: "Pew non-response practice",
    cardOrder: 71,
  },
  {
    id: "A42_lorenz",
    section: "bias", name: "Coverage equity (Lorenz / Gini)",
    short: "Lorenz curve + Gini KPI; compares to universe Gini.",
    requiredInputs: ["points", "universe", "parcels"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "LorenzCurve",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["coverage_gini", "universe_gini"],
    pitfalls: ["Legitimate prioritization inflates Gini"],
    sourceInspiration: "Quantifying Inequities in COVID-19 Vaccine Distribution (medRxiv)",
    cardOrder: 72,
  },
  {
    id: "A43_raking_diag",
    section: "bias", name: "Raking weights diagnostic",
    short: "Weights histogram + max/min/CV + DEFF.",
    requiredInputs: ["responses", "demographics_schema", "acs_tract_profile"],
    nMin: 200, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "RakingWeightsHist",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["cv", "effective_n"],
    pitfalls: ["Weights > 5 produce noisy estimates; weight trimming changes results"],
    sourceInspiration: "Lumley `survey` R package",
    cardOrder: 73,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §8 Comparison / segmentation
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A44_small_multiples",
    section: "compare", name: "Small-multiples KPI grid",
    short: "One row per surveyor; columns = KPIs.",
    requiredInputs: ["points"],
    nMin: 3, roleGate: "admin", mobileVisible: M,
    computeStrategy: "client", vizComponent: "SmallMultiplesGrid",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["axis_scale_consistency"],
    pitfalls: ["Small panels suppress detail"],
    sourceInspiration: "Tufte; Juice Analytics",
    cardOrder: 80,
  },
  {
    id: "A45_block_sparklines",
    section: "compare", name: "Sparklines per block",
    short: "Velocity micro-pattern by sub-area.",
    requiredInputs: ["points", "parcels"],
    nMin: 14, roleGate: "member", mobileVisible: M,
    computeStrategy: "client", vizComponent: "BlockSparklines",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["n"],
    pitfalls: ["Sparkline + label collisions in dense grids"],
    sourceInspiration: "Tufte data-words",
    cardOrder: 81,
  },
  {
    id: "A46_segment_diff",
    section: "compare", name: "Auto-detected segment differences",
    short: "Biggest FDR-corrected gaps between named segments.",
    requiredInputs: ["responses"],
    nMin: 100, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "SegmentDiffList",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["fdr_threshold", "tests_run"],
    pitfalls: ["Multiple testing; subgroup clicking is p-hacking"],
    sourceInspiration: "Benjamini-Hochberg",
    cardOrder: 82,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §9 Inference & uncertainty
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A47_moe",
    section: "inference", name: "Margin-of-error chrome",
    short: "Universal ± bracket on every proportion (90/95% configurable).",
    requiredInputs: ["responses"],
    nMin: 30, roleGate: "guest", mobileVisible: M,
    computeStrategy: "client", vizComponent: "MoeChromeLayer",
    defaultPack: true, m7Wave1: true, stub: true,
    trustSignals: ["confidence_level", "method"],
    pitfalls: ["MoE assumes SRS; clustered designs need DEFF"],
    sourceInspiration: "Kish 1965",
    cardOrder: 90,
  },
  {
    id: "A48_n_min",
    section: "inference", name: "Sample-size insufficient panel",
    short: "Universal — replaces a card body with 'N more needed' + progress.",
    requiredInputs: [],
    nMin: 0, roleGate: "guest", mobileVisible: M,
    computeStrategy: "client", vizComponent: "NMinPlaceholder",
    defaultPack: true, m7Wave1: true, stub: true,
    trustSignals: ["progress_bar", "card_method_link"],
    pitfalls: ["Don't show a noisy chart with a disclaimer — replace the card"],
    sourceInspiration: "Research-grounded best practice",
    cardOrder: 91,
  },
  {
    id: "A49_deff_ci_map",
    section: "inference", name: "DEFF-adjusted CI on map",
    short: "Hatched overlay where lower-CI < threshold.",
    requiredInputs: ["points", "parcels"],
    nMin: 30, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "HatchedCiChoropleth",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["deff", "hatched_meaning"],
    pitfalls: ["Users only see the point estimate"],
    sourceInspiration: "Wilke ch. 16",
    cardOrder: 92,
  },
  {
    id: "A50_mrp",
    section: "inference", name: "Small-area estimation (MRP)",
    short: "Modeled choropleth + 'model-based estimate' badge.",
    requiredInputs: ["responses", "demographics_schema", "acs_tract_profile"],
    nMin: 200, roleGate: "member", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "MrpChoropleth",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["model_link", "modeled_badge"],
    pitfalls: ["Model misspecification; users mistake modeled values for direct estimates"],
    sourceInspiration: "CDC PLACES methodology; Fay-Herriot",
    cardOrder: 93,
  },

  // ───────────────────────────────────────────────────────────────────────────
  // §10 Action-oriented
  // ───────────────────────────────────────────────────────────────────────────
  {
    id: "A51_topk",
    section: "actions", name: "Top-K blocks to revisit",
    short: "Ranked list + map + estimated yield — 'where do we go tomorrow?'.",
    requiredInputs: ["universe", "points", "parcels"],
    nMin: 50, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "TopKBlocks",
    defaultPack: true, m7Wave1: true, stub: false,
    trustSignals: ["ranking_formula", "weights"],
    pitfalls: ["Ranking formula transparency — show what feeds the score"],
    sourceInspiration: "NGP VAN turf-cutting",
    cardOrder: 100,
  },
  {
    id: "A52_f1_queue",
    section: "actions", name: "Follow-ups due (F1 queue)",
    short: "Sortable list + map of un-matched F1 field points.",
    requiredInputs: ["match_status"],
    nMin: 1, roleGate: "member", mobileVisible: M,
    computeStrategy: "postgres", vizComponent: "F1QueueListMap",
    defaultPack: false, m7Wave1: true, stub: false,
    trustSignals: ["n_pending", "oldest_days"],
    pitfalls: ["F1 piling up without response import means no one is closing the loop"],
    sourceInspiration: "FieldSurvey match-status semantics",
    cardOrder: 101,
  },
  {
    id: "A53_anomalies",
    section: "actions", name: "Anomalies needing review",
    short: "Today vs rolling baseline alerts with severity.",
    requiredInputs: ["points"],
    nMin: 14, roleGate: "admin", mobileVisible: M,
    computeStrategy: "python_sidecar", vizComponent: "AnomalyAlertList",
    defaultPack: false, m7Wave1: false, stub: true,
    trustSignals: ["baseline_window", "z_score_per_alert"],
    pitfalls: ["Noisy alerts erode trust — tune severity floor"],
    sourceInspiration: "SRE-style anomaly detection",
    cardOrder: 102,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Convenience accessors
// ─────────────────────────────────────────────────────────────────────────────

export function getCardById(id: string): CardDescriptor | SpatialCardCatalogEntry | undefined {
  return ANALYSES_REGISTRY.find((c) => c.id === id);
}

export function getCardsBySection(section: CardDescriptor["section"]): CardDescriptor[] {
  return ANALYSES_REGISTRY.filter((c) => c.section === section).sort(
    (a, b) => a.cardOrder - b.cardOrder,
  );
}

export function getDefaultPack(): CardDescriptor[] {
  return ANALYSES_REGISTRY.filter((c) => c.defaultPack);
}

export function getWave1OptIns(): CardDescriptor[] {
  return ANALYSES_REGISTRY.filter((c) => c.m7Wave1 && !c.defaultPack);
}

export function getStubs(): CardDescriptor[] {
  return ANALYSES_REGISTRY.filter((c) => c.stub);
}

export const SECTION_ORDER: CardDescriptor["section"][] = [
  "cornerstone",
  "response",
  "spatial",
  "coverage",
  "temporal",
  "qc",
  "quality",
  "bias",
  "compare",
  "inference",
  "actions",
];

export const SECTION_LABELS: Record<CardDescriptor["section"], string> = {
  cornerstone: "Cornerstone",
  response: "§1 Response analytics",
  spatial: "§2 Spatial analytics",
  coverage: "§3 Coverage & completion (AAPOR)",
  temporal: "§4 Temporal patterns",
  qc: "§5 Surveyor / team QC",
  quality: "§6 Data quality",
  bias: "§7 Representativeness",
  compare: "§8 Comparison & segmentation",
  inference: "§9 Inference & uncertainty",
  actions: "§10 Action-oriented",
};

/** Build-time sanity: total catalog count. */
export const CATALOG_COUNT = ANALYSES_REGISTRY.length;
