-- M7 S7: Guest Reports
--
-- Guests can't chat (no Supabase user_id) but they can send a one-shot
-- text + photo + location report to the project admins. This is the
-- backing store for that flow.
--
-- Schema notes:
--   - project_id is FK to projects(id) with ON DELETE CASCADE so reports
--     vanish if the project is deleted.
--   - guest_session_id stores the fs_guest cookie session id at the time
--     of submission so the admin can correlate with other guest activity.
--     We do NOT FK to guest_sessions (sessions expire and rows get pruned;
--     reports outlive their session).
--   - body is TEXT NOT NULL with a 4000-char limit at the app layer; we
--     keep the column unconstrained so we can adjust without a migration.
--   - photo_path is the Storage object path inside the `guest-reports`
--     bucket; null when no photo was attached.
--   - lat/lon optional — guest may decline location.
--   - status defaults to 'new'; admins can mark as 'reviewed' or 'resolved'.
--
-- RLS:
--   - SELECT: project admins only (project_members.role='admin').
--   - INSERT: blocked by RLS; writes go through the service-role API.
--   - UPDATE: admins only.

CREATE TABLE IF NOT EXISTS guest_reports (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id      UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  guest_session_id TEXT NOT NULL,
  guest_name      TEXT,
  title           TEXT NOT NULL,
  body            TEXT NOT NULL,
  photo_path      TEXT,
  lat             DOUBLE PRECISION,
  lon             DOUBLE PRECISION,
  status          TEXT NOT NULL DEFAULT 'new'
                  CHECK (status IN ('new', 'reviewed', 'resolved')),
  reviewed_by     UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewed_at     TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_guest_reports_project_created
  ON guest_reports(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_guest_reports_status
  ON guest_reports(project_id, status, created_at DESC);

ALTER TABLE guest_reports ENABLE ROW LEVEL SECURITY;

-- Admin SELECT
DROP POLICY IF EXISTS "Admins read guest reports for their project" ON guest_reports;
CREATE POLICY "Admins read guest reports for their project"
  ON guest_reports
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = guest_reports.project_id
        AND pm.user_id = auth.uid()
        AND pm.role = 'admin'
    )
  );

-- Admin UPDATE (status / review fields)
DROP POLICY IF EXISTS "Admins update guest reports for their project" ON guest_reports;
CREATE POLICY "Admins update guest reports for their project"
  ON guest_reports
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = guest_reports.project_id
        AND pm.user_id = auth.uid()
        AND pm.role = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM project_members pm
      WHERE pm.project_id = guest_reports.project_id
        AND pm.user_id = auth.uid()
        AND pm.role = 'admin'
    )
  );

-- No INSERT policy: writes go through the service-role POST /api/reports/guest
-- after the HMAC cookie is verified. RLS blocks anon + member writes.

-- Storage bucket for photos. Public read is OFF; access via signed URL
-- generated by the same API route that returns admin-visible reports.
INSERT INTO storage.buckets (id, name, public)
VALUES ('guest-reports', 'guest-reports', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policy: admins can read; service-role bypasses RLS for writes.
DROP POLICY IF EXISTS "Admins read guest-report photos" ON storage.objects;
CREATE POLICY "Admins read guest-report photos"
  ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'guest-reports'
    AND EXISTS (
      SELECT 1 FROM guest_reports gr
      JOIN project_members pm
        ON pm.project_id = gr.project_id
        AND pm.user_id = auth.uid()
        AND pm.role = 'admin'
      WHERE gr.photo_path = storage.objects.name
    )
  );
